name: Feature CI

on:
  push:
    branches: [feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  feature-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      uses: aminya/setup-cpp@v1

    # start test coverage using this tool or gcov
    - name: Install gcovr
      run: sudo apt-get install -y gcovr

    - name: Compile Webserv
      run: make

    - name: Run Code
      run: |
        make run &
        SERVER_PID=$!
        sleep 3 # just to certify that test will run...

    - name: Stop Webserv
      run: kill -SIGINT $SERVER_PID
